### ISSUE TITLE
Check reverse dependencies

### ISSUE THREAD

**Issue by georgheinze** [georgheinze/coxphf#2]
NAMESPACE file of version 1.13 explicitly exported breast.
This is not the case in new version 1.13.1, and likely causing the problem with the reverse dependency with PHInfiniteEstimates.

Please find out how to check reverse dependencies!

**Comment by jrckln** [comment]
The problem was that the data was not saved as an rda file but defined within a R script so it had to be exported. Problem should be solved by latest commit.
