### ISSUE TITLE
Result presentation

### ISSUE THREAD

**Issue by liutiming** [georgheinze/coxphf#5]
Thank you very much for this awesome package!

I wonder what would be the best way to present the result from the package? 

Usually other R stats result (such as `coxph`)can be passed on to the `{broom}` package to convert to a table, which can be subsequently used by packages like `{gtsummary}` to create presentation-ready tables. Results from `coxphf` seems incompatible. I wonder if as the maintainer, you will be interested in making this possible, as suggested by the instructions from the broom package [here](https://cran.r-project.org/web/packages/broom/vignettes/adding-tidiers.html).

**Comment by gregorsteiner** [comment]
Hi, sorry for the delay. In #11, I just added support for `{broom}`.

**Comment by liutiming** [comment]
Many thanks!
